### ISSUE TITLE
Whale 스토어 시립대 키워드로 검색 가능하게 수정하기

### ISSUE THREAD

**Issue by livlikwav** [krescere/Baebongtang#2]
# What

- 웨일 스토어 게시물을 수정하여 '서울시립대', '시립대' 등의 키워드로 검색할 수 있도록 함

# Why

- 현재 '배봉탕' 키워드로만 검색이 가능하다
- '시립대', '서울시립대' 등의 키워드로 검색이 가능해야, '배봉탕'의 존재를 모르는 사용자도 찾아서 사용할 수 있다.

**Comment by shininghyunho** [comment]
검색해보니 따로 키워드 검색을 추가하는 기능은 없어보이고
다른 페이지들 참조해보니 상세기능에 추가하면 검색이 되서
상세기록 추가해서 다시 등록 신청 넣어놨습니다
