### ISSUE TITLE
Whale 스토어 게시물 관리

### ISSUE THREAD

**Issue by livlikwav** [krescere/Baebongtang#3]
# What

웨일 스토어 '배봉탕' 게시물 관리를 tracking 한다.

- 오타 수정
- 소개글 개선
- ... 등

# Why

- 마케팅 측면에서 '배봉탕'이 많은 사람들에게 노출되고, 사용될 수 있도록 고려함.
  - 잘 만드는 것과, 잘 파는 것은 다른 이야기

**Comment by livlikwav** [comment]
# 210422

오타 수정

as-is: -가츠동을 사람하는 사람이-
to-be: -가츠동을 사랑하는 사람이- (혹은 그냥 삭제하고 다른 문구를 넣어도 좋을 듯)

**Comment by shininghyunho** [comment]
일단 지운채로 다시 등록신청 넣어놨습니다
